from django.db import models
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
#Create Portfolio
class Portfolio(models.Model):
    #title = models.CharField(max_length=settings.WIKI_PAGE_TITLE_MAX_LENGTH, unique=True,
                             #help_text="Title of your page.")
    #author = models.ForeignKey(User, on_delete=models.PROTECT,
                               #help_text="The user that posted this article.")
    #slug = models.CharField(max_length=settings.WIKI_PAGE_TITLE_MAX_LENGTH, blank=True, editable=False,
                            #help_text="Unique URL path to access this page. Generated by the system.")
    created = models.DateTimeField(auto_now_add=True,
                                   help_text="The date and time this page was created. Automatically generated when the model saves.")
    document = models.FileField(upload_to='documents/')
