# Generated by Django 2.2.6 on 2019-12-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='picture',
            field=models.ImageField(upload_to='portfolios/covers/'),
        ),
    ]
