# Generated by Django 2.2.6 on 2019-12-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20191206_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
    ]
