# Generated by Django 2.2.6 on 2019-12-06 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20191206_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=140, unique=True),
        ),
    ]
